name: Building app

on:
  push:
    branches:
      - $default-branch
    pull_request:
      - $default-branch
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build -v -r
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          path: |
            ./target/release/github-webhook
