name: Building app

on:
  push:
    branches:
      - main
    paths:
      - 'src/**.rs'
      - 'Cargo.*'
      - '.github/**.ya?ml'
  pull_request:
    branches:
      - main
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - run: rustup update stable && rustup default stable
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build
        run: cargo build -v -r
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: github-webhook-${{ runner.arch }}
          path: |
            ./target/release/github-webhook
